apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ciml-run-training
spec:
  params:
  - name: dataset
    description: Name of the dataset
  - name: experiment
    description: Name of the experiment
  resources:
    inputs:
      - name: ciml
        type: git
      - name: dataset
        type: storage
        targetPath: data/dataset
      - name: experiments
        type: storage
        targetPath: data/_experiments
    outputs:
      resources:
      - name: cimloutput
        type: storage
  steps:

  - name: run-ciml
    image: de.icr.io/ciml/ciml-base:latest
    workingDir: $(inputs.resources.ciml.path)
    env:
    - name: PYTHONPATH
      value: $(inputs.resources.ciml.path)
    - name: LC_ALL
      value: C.UTF-8
    - name: LANG
      value: C.UTF-8
    script: |
      #!/bin/bash
      set -ex

      DATA_DIR=$(dirname $(resources.inputs.dataset.path))
      ln -s $(resources.inputs.dataset.path) $DATA_DIR/$(params.dataset)

      python ciml/trainer.py local_trainer \
        --dataset "$(params.dataset)" \
        --experiment "$(params.experiment)" \
        --data-path $DATA_DIR

      mv $(resources.inputs.ciml.path)/data $(resources.outputs.cimloutput.path)/
