apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ciml-run-all-trainings
spec:
  volumes:
    - name: ciml-data
      configMap:
        name: ciml-data
  params:
  - name: git-resource
    description: Name of the git resource to be used to the training tasks
  - name: experiments-bucket-resource
    description: Name of the bucket resources with experiments
  - name: max-concurrency
    description: Max concurrency for training tasks execution
  - name: data-bucket
    description: Name of the bucket that holds the datasets and experiments
  - name: output-bucket
    description: Name of the bucket where to write trained models to
  resources:
    inputs:
      - name: ciml
        type: git
    outputs:
      - name: runlog
        type: storage
  steps:
  - name: run-ciml-matrix
    image: de.icr.io/ciml/tkn:latest
    workingDir: $(resources.inputs.ciml.path)/scripts
    env:
    - name: GIT_RESOURCE
      value: $(inputs.params.git-resource)
    - name: EXPERIMENTS_BUCKET_RESOURCE
      value: $(inputs.params.experiments-bucket-resource)
    - name: MAX_CONCURRENCY
      value: $(inputs.params.max-concurrency)
    - name: DATA_BUCKET
      value: $(inputs.params.data-bucket)
    - name: OUTPUT_BUCKET
      value: $(inputs.params.output-bucket)
    - name: DATASETS
      value: /data/datasets
    - name: EXPERIMENTS
      value: /data/experiments
    - name: TRAINING_LOG_PATH
      value: $(outputs.resources.runlog.path)
    volumeMounts:
    - name: ciml-data
      mountPath: /data
    command:
    script: |
      #!/bin/bash
      set -ex
      ./run_with_tekton.sh
