project:
  name: ciml
  packages:
    ciml:
      actions:
        cache-data:
          inputs:
            build_name: tempest-full
            data_path: $CIML_DATA_PATH
            s3_url: $S3_URL
            s3_access_key_id: $S3_ACCESS_KEY_ID
            s3_secret_access_key: $S3_SECRET_ACCESS_KEY
      triggers:
        Every12Hours:
          inputs:
            cron: "0 */12 * * *"
