apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-to-image
  labels:
    app: ciml
spec:
  params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: pathToContext
      description:
        The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: imageTag
      description: Tag of the images to be used.
      default: "default"
  resources:
    inputs:
      - name: workspace
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url):$(params.imageTag)
        - --context=$(resources.inputs.workspace.path)/$(params.pathToContext)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-actions
  labels:
    app: ciml
spec:
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: run-deploy
      image: andreaf76/wskdeploy:latest
      script: |
        #!/bin/bash
        set -ex

        $(resources.inputs.workspace.path)/actions/deploy.sh --install
      volumeMounts:
      - name: wskconfig
        mountPath: "/root/"
        readOnly: true
      env:
        - name: CIML_DATA_PATH
          value: s3://cimlrawdata-1
        - name: S3_URL
          value: https://s3.eu-de.cloud-object-storage.appdomain.cloud
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cimls3credentials
              key: s3_access_key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cimls3credentials
              key: s3_secret_access_key
  volumes:
    - name: wskconfig
      secret:
        secretName: cimlwiskconfig
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ciml-action-build-and-deploy
spec:
  params:
    - name: imageTag
      description: Tag of the images to be used.
      default: "default"
  resources:
    - name: src
      type: git
    - name: builtImage
      type: image
  tasks:
  - name: source-to-image-task
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: actions/base-image-no-tf
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: workspace
          resource: src
      outputs:
        - name: builtImage
          resource: builtImage
  - name: deploy-to-openwhisk
    taskRef:
      name: deploy-actions
    runAfter:
      - source-to-image-task
    resources:
      inputs:
        - name: workspace
          resource: src
